# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: deveplop workflow

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'

    - name: generate project
    # - run: expect <<EOF
    #     set timeout -1
    #     spawn make generate
    #     expect "GitHub access token값을 입력 해주세요: "
    #     send -- "$env(GITHUB_ACCESS_TOKEN)\r"
    #     expect eof
    #     EOF
      run: make generate
      # env:
      #   GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    
    - name: Build
      run: | 
        xcodebuild \
        -workspace Pokit.xcworkspace \
        -scheme Pokit \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15 pro,OS=16.0' build
