# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: feature-test

on:
  push:
    branches: [ "feature/*" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: initial mise
      run: |
        curl https://mise.jdx.dev/install.sh | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

    - name: initial tuist
      run: mise install tuist

    - name: Create key.json
      run: |
        mkdir -p fastlane
        echo '{
          "key_id": "${{ secrets.APP_STORE_CONNECT_KEY_ID }}",
          "issuer_id": "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",
          "key": "${{ secrets.APP_STORE_CONNECT_API }}",
          "duration": 1200,
          "in_house": false
        }' > fastlane/key.json

    - name: Match Fastlane
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_URL: ${{ secrets.MATCH_URL }}
      run: fastlane match appstore --readonly

    - name: generate project
      env:
        DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
      run: make release

    - name: Release TestFlight
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_URL: ${{ secrets.MATCH_URL }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
        DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
      run: fastlane beta
